spring:
  datasource:
      username: tdsqlsys_normal
      password: 2MYqLEKqa9gz&iaO^3IY
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.30.144.72:4001/ams?zeroDateTimeBehavior=convertToNull
logging:
  level: 
    root: info    