// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.qmakesoft.akita.protocol;

/**
 * 
 * @author Jerry.Zhao
 *
 */
public final class Protocol {
	private Protocol() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface AkitaMessageOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.qmakesoft.akita.protocol.AkitaMessage)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required int32 code = 1;</code>
		 */
		boolean hasCode();

		/**
		 * <code>required int32 code = 1;</code>
		 */
		int getCode();

		/**
		 * <code>required string messageId = 2;</code>
		 */
		boolean hasMessageId();

		/**
		 * <code>required string messageId = 2;</code>
		 */
		java.lang.String getMessageId();

		/**
		 * <code>required string messageId = 2;</code>
		 */
		com.google.protobuf.ByteString getMessageIdBytes();

		/**
		 * <code>required string message = 3;</code>
		 */
		boolean hasMessage();

		/**
		 * <code>required string message = 3;</code>
		 */
		java.lang.String getMessage();

		/**
		 * <code>required string message = 3;</code>
		 */
		com.google.protobuf.ByteString getMessageBytes();
	}

	/**
	 * Protobuf type {@code com.qmakesoft.akita.protocol.AkitaMessage}
	 */
	public static final class AkitaMessage extends com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:com.qmakesoft.akita.protocol.AkitaMessage)
			AkitaMessageOrBuilder {
		// Use AkitaMessage.newBuilder() to construct.
		private AkitaMessage(com.google.protobuf.GeneratedMessage.Builder builder) {
			super(builder);
		}

		private AkitaMessage() {
			code_ = 0;
			messageId_ = "";
			message_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private AkitaMessage(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						code_ = input.readInt32();
						break;
					}
					case 18: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000002;
						messageId_ = bs;
						break;
					}
					case 26: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000004;
						message_ = bs;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw new RuntimeException(e.setUnfinishedMessage(this));
			} catch (java.io.IOException e) {
				throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
						.setUnfinishedMessage(this));
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.qmakesoft.akita.protocol.Protocol.internal_static_com_qmakesoft_akita_protocol_AkitaMessage_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.qmakesoft.akita.protocol.Protocol.internal_static_com_qmakesoft_akita_protocol_AkitaMessage_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.qmakesoft.akita.protocol.Protocol.AkitaMessage.class,
							com.qmakesoft.akita.protocol.Protocol.AkitaMessage.Builder.class);
		}

		private int bitField0_;
		public static final int CODE_FIELD_NUMBER = 1;
		private int code_;

		/**
		 * <code>required int32 code = 1;</code>
		 */
		@Override
		public boolean hasCode() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 code = 1;</code>
		 */
		@Override
		public int getCode() {
			return code_;
		}

		public static final int MESSAGEID_FIELD_NUMBER = 2;
		private volatile java.lang.Object messageId_;

		/**
		 * <code>required string messageId = 2;</code>
		 */
		@Override
		public boolean hasMessageId() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required string messageId = 2;</code>
		 */
		@Override
		public java.lang.String getMessageId() {
			java.lang.Object ref = messageId_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					messageId_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string messageId = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getMessageIdBytes() {
			java.lang.Object ref = messageId_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				messageId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int MESSAGE_FIELD_NUMBER = 3;
		private volatile java.lang.Object message_;

		/**
		 * <code>required string message = 3;</code>
		 */
		@Override
		public boolean hasMessage() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>required string message = 3;</code>
		 */
		@Override
		public java.lang.String getMessage() {
			java.lang.Object ref = message_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					message_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string message = 3;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getMessageBytes() {
			java.lang.Object ref = message_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				message_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			if (!hasCode()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMessageId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMessage()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, code_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getMessageIdBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getMessageBytes());
			}
			unknownFields.writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, code_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getMessageIdBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getMessageBytes());
			}
			size += unknownFields.getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.qmakesoft.akita.protocol.Protocol.AkitaMessage prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.qmakesoft.akita.protocol.AkitaMessage}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:com.qmakesoft.akita.protocol.AkitaMessage)
				com.qmakesoft.akita.protocol.Protocol.AkitaMessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.qmakesoft.akita.protocol.Protocol.internal_static_com_qmakesoft_akita_protocol_AkitaMessage_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.qmakesoft.akita.protocol.Protocol.internal_static_com_qmakesoft_akita_protocol_AkitaMessage_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.qmakesoft.akita.protocol.Protocol.AkitaMessage.class,
								com.qmakesoft.akita.protocol.Protocol.AkitaMessage.Builder.class);
			}

			// Construct using
			// com.qmakesoft.akita.protocol.Protocol.AkitaMessage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				code_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				messageId_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				message_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.qmakesoft.akita.protocol.Protocol.internal_static_com_qmakesoft_akita_protocol_AkitaMessage_descriptor;
			}

			@Override
			public com.qmakesoft.akita.protocol.Protocol.AkitaMessage getDefaultInstanceForType() {
				return com.qmakesoft.akita.protocol.Protocol.AkitaMessage.getDefaultInstance();
			}

			@Override
			public com.qmakesoft.akita.protocol.Protocol.AkitaMessage build() {
				com.qmakesoft.akita.protocol.Protocol.AkitaMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public com.qmakesoft.akita.protocol.Protocol.AkitaMessage buildPartial() {
				com.qmakesoft.akita.protocol.Protocol.AkitaMessage result = new com.qmakesoft.akita.protocol.Protocol.AkitaMessage(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.code_ = code_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.messageId_ = messageId_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.message_ = message_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.qmakesoft.akita.protocol.Protocol.AkitaMessage) {
					return mergeFrom((com.qmakesoft.akita.protocol.Protocol.AkitaMessage) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.qmakesoft.akita.protocol.Protocol.AkitaMessage other) {
				if (other == com.qmakesoft.akita.protocol.Protocol.AkitaMessage.getDefaultInstance()) {
					return this;
				}
				if (other.hasCode()) {
					setCode(other.getCode());
				}
				if (other.hasMessageId()) {
					bitField0_ |= 0x00000002;
					messageId_ = other.messageId_;
					onChanged();
				}
				if (other.hasMessage()) {
					bitField0_ |= 0x00000004;
					message_ = other.message_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasCode()) {
					return false;
				}
				if (!hasMessageId()) {
					return false;
				}
				if (!hasMessage()) {
					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.qmakesoft.akita.protocol.Protocol.AkitaMessage parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.qmakesoft.akita.protocol.Protocol.AkitaMessage) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int code_;

			/**
			 * <code>required int32 code = 1;</code>
			 */
			@Override
			public boolean hasCode() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 code = 1;</code>
			 */
			@Override
			public int getCode() {
				return code_;
			}

			/**
			 * <code>required int32 code = 1;</code>
			 */
			public Builder setCode(int value) {
				bitField0_ |= 0x00000001;
				code_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 code = 1;</code>
			 */
			public Builder clearCode() {
				bitField0_ = (bitField0_ & ~0x00000001);
				code_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object messageId_ = "";

			/**
			 * <code>required string messageId = 2;</code>
			 */
			@Override
			public boolean hasMessageId() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string messageId = 2;</code>
			 */
			@Override
			public java.lang.String getMessageId() {
				java.lang.Object ref = messageId_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						messageId_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string messageId = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getMessageIdBytes() {
				java.lang.Object ref = messageId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					messageId_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string messageId = 2;</code>
			 */
			public Builder setMessageId(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				messageId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string messageId = 2;</code>
			 */
			public Builder clearMessageId() {
				bitField0_ = (bitField0_ & ~0x00000002);
				messageId_ = getDefaultInstance().getMessageId();
				onChanged();
				return this;
			}

			/**
			 * <code>required string messageId = 2;</code>
			 */
			public Builder setMessageIdBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				messageId_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object message_ = "";

			/**
			 * <code>required string message = 3;</code>
			 */
			@Override
			public boolean hasMessage() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>required string message = 3;</code>
			 */
			@Override
			public java.lang.String getMessage() {
				java.lang.Object ref = message_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						message_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string message = 3;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getMessageBytes() {
				java.lang.Object ref = message_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					message_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string message = 3;</code>
			 */
			public Builder setMessage(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				message_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string message = 3;</code>
			 */
			public Builder clearMessage() {
				bitField0_ = (bitField0_ & ~0x00000004);
				message_ = getDefaultInstance().getMessage();
				onChanged();
				return this;
			}

			/**
			 * <code>required string message = 3;</code>
			 */
			public Builder setMessageBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				message_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:com.qmakesoft.akita.protocol.AkitaMessage)
		}

		// @@protoc_insertion_point(class_scope:com.qmakesoft.akita.protocol.AkitaMessage)
		private static final com.qmakesoft.akita.protocol.Protocol.AkitaMessage DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new com.qmakesoft.akita.protocol.Protocol.AkitaMessage();
		}

		public static com.qmakesoft.akita.protocol.Protocol.AkitaMessage getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		public static final com.google.protobuf.Parser<AkitaMessage> PARSER = new com.google.protobuf.AbstractParser<AkitaMessage>() {
			@Override
			public AkitaMessage parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				try {
					return new AkitaMessage(input, extensionRegistry);
				} catch (RuntimeException e) {
					if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
						throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
					}
					throw e;
				}
			}
		};

		@Override
		public com.google.protobuf.Parser<AkitaMessage> getParserForType() {
			return PARSER;
		}

		@Override
		public com.qmakesoft.akita.protocol.Protocol.AkitaMessage getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_com_qmakesoft_akita_protocol_AkitaMessage_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_qmakesoft_akita_protocol_AkitaMessage_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\016protocol.proto\022\034com.qmakesoft.akita.pr"
				+ "otocol\"@\n\014AkitaMessage\022\014\n\004code\030\001 \002(\005\022\021\n\t"
				+ "messageId\030\002 \002(\t\022\017\n\007message\030\003 \002(\t" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			@Override
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_com_qmakesoft_akita_protocol_AkitaMessage_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_com_qmakesoft_akita_protocol_AkitaMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_com_qmakesoft_akita_protocol_AkitaMessage_descriptor,
				new java.lang.String[] { "Code", "MessageId", "Message", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
